version: "3.8"

services:
  postgres:
    # image: postgres:15.3-alpine
    build: ./postgres-init
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_MULTIPLE_DATABASES: raports,logs
    networks:
      - database-network

  adminer:
    container_name: db-adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - database-network

  supercronic:
    build: ./cron
    command: supercronic crontab
    volumes:
      - ./backup:/backup
    networks:
      - database-network

networks:
  database-network:
    name: database-net
# volumes:
#   logs:
#     driver_opts:
#       type: cifs
#       o: "username=docker,password=docker4545docker"
#       device: "//192.168.5.80/production_files/logs/mutoh"
